### ISSUE TITLE
Action fails on "Commit autopep8 changes"

### ISSUE THREAD

**Issue by PuneetKohli** [peter-evans/autopep8#34]
We have often got this failure and are unable to debug it:

![image](https://user-images.githubusercontent.com/8395443/69280499-6032cd80-0b9b-11ea-9355-196ecb369fbc.png)

Our workflow:
1. Submit PR
2. Run Autopep8 action 
3. Immediately commit code to the same branch/PR

The action code is attached below for reference:

```
name: autopep8
on: pull_request
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.1.0
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1.1.0
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'Redacted'
          git config --global user.email 'redacted@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.self_lint }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "self: lint fix"
          git push
```

**Comment by PuneetKohli** [comment]
This is based on : https://github.com/peter-evans/autopep8#direct-push-with-on-pull_request-workflows

**Comment by peter-evans** [comment]
Hi @PuneetKohli, thank you for opening this issue.

I think this is due to some recent changes to the `actions/checkout` action. Please try this updated workflow that should fix the problem.
```
name: autopep8
on: pull_request
jobs:
  autopep8:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1.1.0
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'Peter Evans'
          git config --global user.email 'peter-evans@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated autopep8 fixes"
          git push
```
I will update the documentation to reflect this new change.
